-- AlterTable
ALTER TABLE "Vendor" ADD COLUMN     "campaignLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "chatbotLimit" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "formLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "galleryLimit" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "leadLimit" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN     "planType" TEXT NOT NULL DEFAULT 'free',
ADD COLUMN     "templateLimit" INTEGER NOT NULL DEFAULT 10;
